using System.Collections.Generic;

namespace Metrics
{
	public class EventsLists
	{
		public static List<Events> EventsForSessionHistory = new List<Events>
		{
			Events.PlayerStat,
			Events.MultiplayerRaceComplete,
			Events.ListRefresh,
			Events.RequestMatches,
			Events.PrizeCardWon,
			Events.CarPuzzleCompleted,
			Events.MultiplayerPurchase,
			Events.WinStreakComplete
		};

		public static List<Parameters> Defaults = new List<Parameters>
		{
			Parameters.Ver,
			Parameters.Snapshot,
			Parameters.Platform,
			Parameters.brnch,
			Parameters.bckt,
			Parameters.tst,
			Parameters.Banned
		};

	    public static Dictionary<Events, List<Parameters>> ParametersForEvent = new Dictionary<Events, List<Parameters>>
	    {
		    {
			    Events.Tier1CrewMember1FirstRace,
			    new List<Parameters>
			    {
				    Parameters.FirstTier1Crew1Race
			    }
		    },
		    {
			    Events.Tier1CrewMember2FirstRace,
			    new List<Parameters>
			    {
				    Parameters.FirstTier1Crew2Race
			    }
		    },
		    {
			    Events.Tier1CrewMember3FirstRace,
			    new List<Parameters>
			    {
				    Parameters.FirstTier1Crew3Race
			    }
		    },
		    {
			    Events.Tier1CrewMember3_2FirstRace,
			    new List<Parameters>
			    {
				    Parameters.FirstTier1Crew32Race
			    }
		    },
		    {
			    Events.Tier1CrewMember4FirstRace,
			    new List<Parameters>
			    {
				    Parameters.FirstTier1Crew4Race
			    }
		    },
		    {
			    Events.Tier1CrewMember4_2FirstRace,
			    new List<Parameters>
			    {
				    Parameters.FirstTier1Crew42Race
			    }
		    },
		    {
			    Events.Tier1CrewMember4_3FirstRace,
			    new List<Parameters>
			    {
				    Parameters.FirstTier1Crew43Race
			    }
		    },
		    {
			    Events.FirstBeginnerRegulationRaceAttemped,
			    new List<Parameters>
			    {
				    Parameters.FirstEasyRegulationRace
			    }
		    },
		    {
			    Events.FirstAmateurRegulationRaceAttemped,
			    new List<Parameters>
			    {
				    Parameters.FirstNormalRegulationRace
			    }
		    },
		    {
			    Events.FirstHardRegulationRaceAttemped,
			    new List<Parameters>
			    {
				    Parameters.FirstHardRegulationRace
			    }
		    },
		    {
			    Events.Tier1CrewMember1Race,
			    new List<Parameters>
			    {
				    Parameters.RaceCountToWinCrewMember1
			    }
		    },
		    {
			    Events.Tier1CrewMember2Race,
			    new List<Parameters>
			    {
				    Parameters.RaceCountToWinCrewMember2
			    }
		    },
		    {
			    Events.Tier1CrewMember3Race,
			    new List<Parameters>
			    {
				    Parameters.RaceCountToWinCrewMember3
			    }
		    },
		    {
			    Events.Tier1CrewMember3_2Race,
			    new List<Parameters>
			    {
				    Parameters.RaceCountToWinCrewMember32
			    }
		    },
		    {
			    Events.Tier1CrewMember4Race,
			    new List<Parameters>
			    {
				    Parameters.RaceCountToWinCrewMember4
			    }
		    },
		    {
			    Events.Tier1CrewMember4_2Race,
			    new List<Parameters>
			    {
				    Parameters.RaceCountToWinCrewMember43
			    }
		    },
		    {
	            Events.StartGT,
	            new List<Parameters>
	            {
	                Parameters.OSVersion,
	                Parameters.lgdin,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.BXp,
	                Parameters.Bfuel,
	                Parameters.PLvl,
	                Parameters.CmlCr,
	                Parameters.CmlSns,
	                Parameters.CmlUpg,
	                Parameters.CmlRCmp,
	                Parameters.CmlMchR,
	                Parameters.CmlCsh,
	                Parameters.CmlGld,
	                Parameters.PinProg,
	                Parameters.GraphicsAPI,
	                Parameters.AssetQuality
	            }
	        },
	        {
	            Events.SocialInteraction,
	            new List<Parameters>
	            {
	                Parameters.Pltfrm,
	                Parameters.Intfrm,
	                Parameters.Cmltwt,
	                Parameters.Cmlfb,
	                Parameters.PLvl,
	                Parameters.PCr,
	                Parameters.DCsh,
	                Parameters.DGld,
	                Parameters.CmlRCmp,
	                Parameters.CmlCsh,
	                Parameters.CmlGld,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.CmlCshPur,
	                Parameters.CmlGldPur,
	                Parameters.CmlCr
	            }
	        },
	        {
	            Events.PurchaseItem,
	            new List<Parameters>
	            {
	                Parameters.DCsh,
	                Parameters.DGld,
	                Parameters.DXp,
	                Parameters.Dfuel,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.BXp,
	                Parameters.Bfuel,
	                Parameters.PCr,
	                Parameters.PCrPP,
	                Parameters.PCrPUpgdPP,
	                Parameters.MlstRce,
	                Parameters.PLvl,
	                Parameters.CmlCr,
	                Parameters.CmlSns,
	                Parameters.CmlUpg,
	                Parameters.CmlRCmp,
	                Parameters.CmlMchR,
	                Parameters.CmlCsh,
	                Parameters.CmlGld,
	                Parameters.Itm,
	                Parameters.ItmClss,
	                Parameters.Shortcut,
	                Parameters.Upsl,
	                Parameters.RecVer,
	                Parameters.QNam,
	                Parameters.LPos,
	                Parameters.Friends,
	                Parameters.FriendsInCar,
	                Parameters.CmlStars,
	                Parameters.CarStars,
	                Parameters.ThreeStarCars,
	                Parameters.FriendUpgrade,
	                Parameters.PinProg
	            }
	        },
	        {
	            Events.UserLogin,
	            new List<Parameters>
	            {
	                Parameters.baid,
	                Parameters.nmcoreid,
	                Parameters.openUDID,
	                Parameters.mac,
	                Parameters.MlstRce,
	                Parameters.PLvl,
	                Parameters.CmlCr,
	                Parameters.CmlSns,
	                Parameters.CmlUpg,
	                Parameters.CmlRCmp,
	                Parameters.CmlMchR,
	                Parameters.CmlCsh,
	                Parameters.CmlGld
	            }
	        },
	        {
	            Events.InviteFriend,
	            new List<Parameters>
	            {
	                Parameters.DCsh,
	                Parameters.DGld,
	                Parameters.DXp,
	                Parameters.Dfuel,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.BXp,
	                Parameters.Bfuel,
	                Parameters.MlstRce,
	                Parameters.PLvl,
	                Parameters.CmlCr,
	                Parameters.CmlSns,
	                Parameters.CmlUpg,
	                Parameters.CmlRCmp,
	                Parameters.CmlMchR,
	                Parameters.CmlCsh,
	                Parameters.CmlGld,
	                Parameters.QNam,
	                Parameters.InvtTyp
	            }
	        },
	        {
	            Events.MultiplayerRaceComplete,
	            new List<Parameters>
	            {
	                Parameters.PResult,
	                Parameters.PPDelta,
	                Parameters.RPDelta,
	                Parameters.RP,
	                Parameters.PCr,
	                Parameters.OpCr,
	                Parameters.Consumables,
	                Parameters.Rematch,
	                Parameters.MPRaceTotal,
	                Parameters.MPConsecWin,
	                Parameters.MPDiff,
	                Parameters.MPElDiff,
	                Parameters.StreakType,
	                Parameters.ConsumableEN,
	                Parameters.ConsumableNI,
	                Parameters.ConsumableTY,
	                Parameters.ConsumableBL,
	                Parameters.ConsumableWhole,
	                Parameters.StreakNo,
	                Parameters.StreakRescued,
	                Parameters.PFin,
	                Parameters.OpFin,
	                Parameters.PCrPP,
	                Parameters.StreakDiff,
	                Parameters.MPEvDiff,
	                Parameters.MlstRce,
	                Parameters.PinProg,
	                Parameters.MPEvtID,
	                Parameters.SsnAwded,
	                Parameters.LeadPos
	            }
	        },
	        {
	            Events.ListRefresh,
	            new List<Parameters>
	            {
	                Parameters.PCrPP,
	                Parameters.RP,
	                Parameters.P1PPDelta,
	                Parameters.P2PPDelta,
	                Parameters.P3PPDelta,
	                Parameters.P4PPDelta,
	                Parameters.P5PPDelta,
	                Parameters.P6PPDelta
	            }
	        },
	        {
	            Events.PrizeCardWon,
	            new List<Parameters>
	            {
	                Parameters.CardType,
	                Parameters.CarPart,
	                Parameters.FuelPips,
	                Parameters.SessionCardCount,
	                Parameters.CardsWon
	            }
	        },
	        {
	            Events.CarPuzzleCompleted,
	            new List<Parameters>
	            {
	                Parameters.CarCompleted,
	                Parameters.PurchaseSportsPack,
	                Parameters.RTier,
	                Parameters.MPRaceTotal,
	                Parameters.PaidPuzzlePieces
	            }
	        },
	        {
	            Events.WinStreakComplete,
	            new List<Parameters>
	            {
	                Parameters.Result,
	                Parameters.StreakType,
	                Parameters.RaceCount,
	                Parameters.PlayerCar,
	                Parameters.RPStreakDelta,
	                Parameters.WinningsCash,
	                Parameters.WinningsCards,
	                Parameters.Race1PPDelta,
	                Parameters.Race1RPDelta,
	                Parameters.Race1Result,
	                Parameters.Race2PPDelta,
	                Parameters.Race2RPDelta,
	                Parameters.Race2Result,
	                Parameters.Race3PPDelta,
	                Parameters.Race3RPDelta,
	                Parameters.Race3Result,
	                Parameters.Race4PPDelta,
	                Parameters.Race4RPDelta,
	                Parameters.Race4Result,
	                Parameters.Race5PPDelta,
	                Parameters.Race5RPDelta,
	                Parameters.Race5Result,
	                Parameters.Race6PPDelta,
	                Parameters.Race6RPDelta,
	                Parameters.Race6Result,
	                Parameters.StreakNo,
	                Parameters.StreakRescued,
	                Parameters.PCrPP,
	                Parameters.StreakDiff,
	                Parameters.MPDiff,
	                Parameters.MPElDiff,
	                Parameters.MPEvDiff,
	                Parameters.MlstRce
	            }
	        },
	        {
	            Events.EndGT,
	            new List<Parameters>
	            {
	                Parameters.lgdin,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.BXp,
	                Parameters.Bfuel,
	                Parameters.MlstRce,
	                Parameters.PLvl,
	                Parameters.CmlCr,
	                Parameters.CmlSns,
	                Parameters.CmlUpg,
	                Parameters.CmlRCmp,
	                Parameters.CmlMchR,
	                Parameters.CmlCsh,
	                Parameters.CmlGld,
	                Parameters.PinProg
	            }
	        },
	        {
	            Events.CompleteRace,
	            new List<Parameters>
	            {
	                Parameters.DCsh,
	                Parameters.DGld,
	                Parameters.DXp,
	                Parameters.Dfuel,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.BXp,
	                Parameters.Bfuel,
	                Parameters.Rname,
	                Parameters.RDiff,
	                Parameters.RTier,
	                Parameters.Rlength,
	                Parameters.PCr,
	                Parameters.PCrPP,
	                Parameters.Pntrs,
	                Parameters.PResult,
	                Parameters.PFin,
	                Parameters.OpCr,
	                Parameters.OpCrPP,
	                Parameters.OpFin,
	                Parameters.PPrfShft,
	                Parameters.PGdShft,
	                Parameters.PErlShft,
	                Parameters.PLteShft,
	                Parameters.PTrmSpd,
	                Parameters.PBstAwd,
	                Parameters.P0to60,
	                Parameters.P0to100,
	                Parameters.PGrtLnch,
	                Parameters.PMchR,
	                Parameters.MlstRce,
	                Parameters.PLvl,
	                Parameters.CmlCr,
	                Parameters.CmlSns,
	                Parameters.CmlUpg,
	                Parameters.CmlRCmp,
	                Parameters.CmlMchR,
	                Parameters.CmlCsh,
	                Parameters.CmlGld,
	                Parameters.CmlRly,
	                Parameters.Eng,
	                Parameters.Bdy,
	                Parameters.Trns,
	                Parameters.Trs,
	                Parameters.Trb,
	                Parameters.Nit,
	                Parameters.Intk,
	                Parameters.QNam,
	                Parameters.LPos,
	                Parameters.DLPos,
	                Parameters.Friends,
	                Parameters.FriendsInCar,
	                Parameters.CmlStars,
	                Parameters.ThreeStarCars,
	                Parameters.CarStars,
	                Parameters.StarsWon,
	                Parameters.FriendRaced,
	                Parameters.DayNum,
	                Parameters.PinProg
	            }
	        },
	        {
	            Events.RelayRaceComplete,
	            new List<Parameters>
	            {
	                Parameters.DCsh,
	                Parameters.DGld,
	                Parameters.DXp,
	                Parameters.RTier,
	                Parameters.Rname,
	                Parameters.PinProg,
	                Parameters.PFin,
	                Parameters.PResult,
	                Parameters.CmlGld,
	                Parameters.CmlCsh,
	                Parameters.CmlRly,
	                Parameters.MlstRce,
	                Parameters.RlyLngth,
	                Parameters.RlyResult
	            }
	        },
	        {
	            Events.CarPicked,
	            new List<Parameters>
	            {
	                Parameters.Plc,
	                Parameters.PinProg,
	                Parameters.CChc,
	                Parameters.RTier
	            }
	        },
	        {
	            Events.HeyYou,
	            ParametersLists.Empty
	        },
	        {
	            Events.PressGas,
	            ParametersLists.Empty
	        },
	        {
	            Events.TeachShiftUp,
	            ParametersLists.Empty
	        },
	        {
	            Events.WarnEarlyShift,
	            ParametersLists.Empty
	        },
	        {
	            Events.WarnWheelspinStart,
	            ParametersLists.Empty
	        },
	        {
	            Events.WarnIdleStart,
	            ParametersLists.Empty
	        },
	        {
	            Events.WarnBadThrottle,
	            ParametersLists.Empty
	        },
	        {
	            Events.NowDo2ndRace,
	            ParametersLists.Empty
	        },
	        {
	            Events.FocusGoodStart,
	            ParametersLists.Empty
	        },
	        {
	            Events.YouCanDoBetter,
	            ParametersLists.Empty
	        },
	        {
	            Events.WeHaveContender,
	            ParametersLists.Empty
	        },
	        {
	            Events.FootRace,
	            ParametersLists.Empty
	        },
	        {
	            Events.TimeToDeliverCar,
	            ParametersLists.Empty
	        },
	        {
	            Events.TryAgainTapCar,
	            ParametersLists.Empty
	        },
	        {
	            Events.TheseAreRegulationRaces,
	            ParametersLists.Empty
	        },
	        {
	            Events.TheseAreCrewRaces,
	            ParametersLists.Empty
	        },
	        {
	            Events.IntroToCrews,
	            ParametersLists.Empty
	        },
	        {
	            Events.PriorTo1stCrewRace,
	            ParametersLists.Empty
	        },
	        {
	            Events.PapaGrief,
	            ParametersLists.Empty
	        },
	        {
	            Events.AgentConsoles1stCrewDefeat,
	            ParametersLists.Empty
	        },
	        {
	            Events.TapToUpgrade,
	            ParametersLists.Empty
	        },
	        {
	            Events.TapToShop,
	            ParametersLists.Empty
	        },
	        {
	            Events.TheseAreLadderRaces,
	            ParametersLists.Empty
	        },
	        {
	            Events.MechanicTune,
	            ParametersLists.Empty
	        },
	        {
	            Events.AgentIntroToUpgrades,
	            ParametersLists.Empty
	        },
	        {
	            Events.AgentSuggestsUpgrade,
	            ParametersLists.Empty
	        },
	        {
	            Events.NoReallyYouShouldBuyUpgrade,
	            ParametersLists.Empty
	        },
	        {
	            Events.Bought1stUpgrade,
	            ParametersLists.Empty
	        },
	        {
	            Events.TheseAreDailyBattles,
	            ParametersLists.Empty
	        },
	        {
	            Events.MoreDailyBattles,
	            ParametersLists.Empty
	        },
	        {
	            Events.TheseAreChallengeRaces,
	            ParametersLists.Empty
	        },
	        {
	            Events.ThisIsNitrous,
	            ParametersLists.Empty
	        },
	        {
	            Events.DealerShipTour,
	            ParametersLists.Empty
	        },
	        {
	            Events.TapCarDealer,
	            ParametersLists.Empty
	        },
	        {
	            Events.FacebookSignIn,
	            ParametersLists.Empty
	        },
	        {
	            Events.FacebookNotNowThx,
	            ParametersLists.Empty
	        },
	        {
	            Events.YouShouldBuyBetterCar,
	            ParametersLists.Empty
	        },
	        {
	            Events.BuyFirstCar,
	            ParametersLists.TutorialShowroomEventsParameters
	        },
	        {
	            Events.BuyThisCar,
	            ParametersLists.TutorialShowroomEventsParameters
	        },
	        {
	            Events.CancelThisCar,
	            ParametersLists.TutorialShowroomEventsParameters
	        },
	        {
	            Events.DeliverThisCar,
	            ParametersLists.TutorialShowroomEventsParameters
	        },
	        {
	            Events.NotEnough,
	            ParametersLists.NotEnoughEventParameters
	        },
	        {
	            Events.Complete1stTutRace,
	            ParametersLists.TutorialRacesEventsParameters
	        },
	        {
	            Events.Complete2ndTutRace,
	            ParametersLists.TutorialRacesEventsParameters
	        },
	        {
	            Events.CompleteRegTutRace,
	            ParametersLists.TutorialRacesEventsParameters
	        },
	        {
	            Events.CompleteCrewTutRace,
	            ParametersLists.TutorialRacesEventsParameters
	        },
	        {
	            Events.LevelUp,
	            new List<Parameters>
	            {
					Parameters.Level,
					Parameters.DCsh,
	                Parameters.DGld,
	                Parameters.DXp,
	                Parameters.Dfuel,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.BXp,
	                Parameters.Bfuel,
	                Parameters.MlstRce,
	                Parameters.PLvl,
	                Parameters.CmlCr,
	                Parameters.CmlSns,
	                Parameters.CmlUpg,
	                Parameters.CmlRCmp,
	                Parameters.CmlMchR,
	                Parameters.CmlCsh,
	                Parameters.CmlGld
	            }
	        },
	        {
	            Events.TierCompleted,
	            new List<Parameters>
	            {
	                Parameters.RTier,
	                Parameters.CmlRCmp,
	                Parameters.CmlCshPur,
	                Parameters.CmlGldPur,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.PLvl,
	                Parameters.CmlUpg,
	                Parameters.PCr
	            }
	        },
	        {
	            Events.PlayerStat,
	            new List<Parameters>
	            {
	                Parameters.RP,
	                Parameters.MPRaceTotal,
	                Parameters.MPWinRate,
	                Parameters.CmlRCmp,
	                Parameters.SPWinRate,
	                Parameters.SessionNum,
	                Parameters.CardsWon,
	                Parameters.CmlCr
	            }
	        },
	        {
	            Events.MultiplayerPurchase,
	            new List<Parameters>
	            {
	                Parameters.Type,
	                Parameters.CostCash,
	                Parameters.CostGold,
	                Parameters.Duration,
	                Parameters.PieceID,
	                Parameters.TSU,
	                Parameters.PreUpgradeDelta,
	                Parameters.EliteLivID,
	                Parameters.MlstRce,
	                Parameters.StreakType,
	                Parameters.H1,
	                Parameters.H2,
	                Parameters.H3,
	                Parameters.H4,
	                Parameters.H5,
	                Parameters.H6,
	                Parameters.H7,
	                Parameters.H8,
	                Parameters.StreakNo,
	                Parameters.StreakRescued,
	                Parameters.CostAd,
	                Parameters.PinProg,
	                Parameters.MPDiff,
	                Parameters.MPElDiff,
	                Parameters.MPEvDiff,
	                Parameters.PCr,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.DCsh,
	                Parameters.DGld
	            }
	        },
	        {
	            Events.RequestMatches,
	            new List<Parameters>
	            {
	                Parameters.RP,
	                Parameters.PerfTime,
	                Parameters.MPConsecWin,
	                Parameters.MPDiff,
	                Parameters.MPElDiff,
	                Parameters.StreakType
	            }
	        },
	        {
	            Events.StreakRescue,
	            new List<Parameters>
	            {
	                Parameters.RP,
	                Parameters.StreakType,
	                Parameters.StreakNo,
	                Parameters.StreakRaceNo,
	                Parameters.Rescue,
	                Parameters.StreakRescued,
	                Parameters.Bfuel,
	                Parameters.LPos,
	                Parameters.RPBoost,
	                Parameters.ConsumableEN,
	                Parameters.ConsumableNI,
	                Parameters.ConsumableTY,
	                Parameters.ConsumableBL,
	                Parameters.ConsumableWhole
	            }
	        },
	        {
	            Events.ReplayVSSimulationTimeCheck,
	            new List<Parameters>
	            {
	                Parameters.ReplayUserID,
	                Parameters.OpCr,
	                Parameters.SimRaceTime,
	                Parameters.ReplayRaceTime,
	                Parameters.SimReplayRaceDeltaTime,
	                Parameters.ReplayType
	            }
	        },
	        {
	            Events.PssstKid,
	            ParametersLists.Empty
	        },
	        {
	            Events.TapsMultiplayer,
	            ParametersLists.Empty
	        },
	        {
	            Events.FreeEntryOK,
	            ParametersLists.Empty
	        },
	        {
	            Events.TapsWorld,
	            ParametersLists.Empty
	        },
	        {
	            Events.GoRaceMP,
	            ParametersLists.Empty
	        },
	        {
	            Events.BackOut,
	            ParametersLists.Empty
	        },
	        {
	            Events.HeyKid,
	            ParametersLists.Empty
	        },
	        {
	            Events.PlayerlistOK,
	            ParametersLists.Empty
	        },
	        {
	            Events.SelectOpponent1,
	            ParametersLists.Empty
	        },
	        {
	            Events.OKRaceTeamIntro,
	            ParametersLists.Empty
	        },
	        {
	            Events.YesHireRaceTeam,
	            ParametersLists.Empty
	        },
	        {
	            Events.NoHireRaceTeam,
	            ParametersLists.Empty
	        },
	        {
	            Events.HireMember,
	            ParametersLists.Empty
	        },
	        {
	            Events.ContinueStreak,
	            ParametersLists.Empty
	        },
	        {
	            Events.Bank,
	            ParametersLists.Empty
	        },
	        {
	            Events.UnBank,
	            ParametersLists.Empty
	        },
	        {
	            Events.ConfirmBank,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace1Win,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace1Lose,
	            ParametersLists.Empty
	        },
	        {
	            Events.GreatJob,
	            ParametersLists.Empty
	        },
	        {
	            Events.NextOpponent,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace2Win,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace2Lose,
	            ParametersLists.Empty
	        },
	        {
	            Events.TwoDown,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace3Win,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace3Lose,
	            ParametersLists.Empty
	        },
	        {
	            Events.NextOneCard,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace4Win,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace4Lose,
	            ParametersLists.Empty
	        },
	        {
	            Events.OneCardGood,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace5Win,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace5Lose,
	            ParametersLists.Empty
	        },
	        {
	            Events.GonnaBeRich,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace6Win,
	            ParametersLists.Empty
	        },
	        {
	            Events.MPRace6Lose,
	            ParametersLists.Empty
	        },
	        {
	            Events.FrankieFeelsFine,
	            ParametersLists.Empty
	        },
	        {
	            Events.HeresYourCards,
	            ParametersLists.Empty
	        },
	        {
	            Events.IKnowHowToLose,
	            ParametersLists.Empty
	        },
	        {
	            Events.SoreLoserLeavelist,
	            ParametersLists.Empty
	        },
	        {
	            Events.StickWithItStay,
	            ParametersLists.Empty
	        },
	        {
	            Events.TapPrizeCard,
	            ParametersLists.Empty
	        },
	        {
	            Events.ComeBackSoon,
	            ParametersLists.Empty
	        },
	        {
	            Events.FirstCarPartPrize,
	            ParametersLists.Empty
	        },
	        {
	            Events.PrizeGalleryShown,
	            ParametersLists.Empty
	        },
	        {
	            Events.EliteClubIntro,
	            ParametersLists.Empty
	        },
	        {
	            Events.TapElitePin,
	            ParametersLists.Empty
	        },
	        {
	            Events.OKEliteTrackSide,
	            ParametersLists.Empty
	        },
	        {
	            Events.CongratsUsePro,
	            ParametersLists.Empty
	        },
	        {
	            Events.SportsPackNag,
	            ParametersLists.Empty
	        },
	        {
	            Events.ProfileMigrate,
	            ParametersLists.Profile
	        },
	        {
	            Events.ProfileCheat,
	            ParametersLists.Profile
	        },
	        {
	            Events.ProfileRecover,
	            new List<Parameters>
	            {
	                Parameters.baid,
	                Parameters.openUDID,
	                Parameters.mac,
	                Parameters.RP,
	                Parameters.BCsh,
	                Parameters.BGld,
	                Parameters.ProfileRecoveryResult
	            }
	        },
	        {
	            Events.SeasonPrize,
	            new List<Parameters>
	            {
	                Parameters.SsnAwded,
	                Parameters.SsnPID,
	                Parameters.SsnAwdT
	            }
	        },
	        {
	            Events.OfferWallAwardGold,
	            new List<Parameters>
	            {
	                Parameters.DGld,
	                Parameters.OWPvr,
	                Parameters.baid,
	                Parameters.PLvl,
	                Parameters.MlstRce,
	                Parameters.CmlRCmp,
	                Parameters.CmlSns
	            }
	        },
	        {
	            Events.AdStaticInterstitialDisplayed,
	            new List<Parameters>
	            {
	                Parameters.AdNwk,
	                Parameters.AdSpace,
	                Parameters.AdRaces,
	                Parameters.AdsPerSession,
	                Parameters.Bfuel,
	                Parameters.Result
	            }
	        },
	        {
	            Events.AdUserStartV4R,
	            ParametersLists.AdsDefault
	        },
	        {
	            Events.AdUserCancelV4R,
	            ParametersLists.AdsDefault
	        },
	        {
	            Events.AdUserV4RStopEarly,
	            ParametersLists.AdsDefault
	        },
	        {
	            Events.AdUserV4RComplete,
	            ParametersLists.AdsDefault
	        },
	        {
	            Events.AdFailedPrecacheV4R,
	            ParametersLists.AdsDefault
	        },
	        {
	            Events.MemoryValidatorFailed126,
	            new List<Parameters>
	            {
	                Parameters.ValueIdentifier,
	                Parameters.ProfileValue,
	                Parameters.MangledValue,
	                Parameters.UnmangledValue,
	                Parameters.InvokedBy
	            }
	        },
	        {
	            Events.IAPPurchaseDiagnostic,
	            new List<Parameters>
	            {
	                Parameters.CSRID,
	                Parameters.PurchaseData
	            }
	        },
	        {
	            Events.CollectReward,
	            new List<Parameters>
	            {
	                Parameters.Friends,
	                Parameters.CmlStars,
	                Parameters.ThreeStarCars,
	                Parameters.FriendsRaces,
	                Parameters.FriendsRacesWon,
	                Parameters.PCr,
	                Parameters.RewardType,
	                Parameters.RewardFor,
	                Parameters.RewardAmount
	            }
	        },
	        {
	            Events.FacebookLogin,
	            new List<Parameters>
	            {
	                Parameters.AllFBFriends,
	                Parameters.CmlStars,
	                Parameters.ThreeStarCars,
	                Parameters.FriendsRaces,
	                Parameters.FriendsRacesWon,
	                Parameters.FriendsCarsWon,
	                Parameters.FriendsGold
	            }
	        },
	        {
	            Events.SyncFriendsRecieved,
	            new List<Parameters>
	            {
	                Parameters.Friends,
	                Parameters.InitialFriends,
	                Parameters.PeakFriends,
	                Parameters.CmlStars,
	                Parameters.ThreeStarCars,
	                Parameters.FriendsRaces,
	                Parameters.FriendsRacesWon,
	                Parameters.FriendsCarsWon,
	                Parameters.FriendsGold
	            }
	        },
	        {
	            Events.FriendsInviteFriends,
	            new List<Parameters>
	            {
	                Parameters.SocialPlatform,
	                Parameters.Friends,
	                Parameters.CmlStars,
	                Parameters.FriendsRaces,
	                Parameters.ThreeStarCars,
	                Parameters.FriendsRaces,
	                Parameters.FriendsRacesWon,
	                Parameters.FriendsInv,
	                Parameters.CmlFriendsInv,
	                Parameters.InitialFriends,
	                Parameters.PeakFriends
	            }
	        },
	        {
	            Events.rwf_tut_001,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_002,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_002a,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_002b,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_002c,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_003,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_004,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_005,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_006,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_007,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_007a,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_008,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_010,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_012,
	            new List<Parameters>()
	        },
	        {
	            Events.rwf_tut_009,
	            new List<Parameters>
	            {
	                Parameters.Friends,
	                Parameters.HasRecievedFriendSync
	            }
	        },
	        {
	            Events.rwf_tut_011,
	            new List<Parameters>
	            {
	                Parameters.PCr
	            }
	        },
	        {
	            Events.StreakChain,
	            new List<Parameters>
	            {
	                Parameters.StreakNo,
	                Parameters.Continue,
	                Parameters.Bfuel,
	                Parameters.LPos,
	                Parameters.RPBoost,
	                Parameters.StreakType,
	                Parameters.ConsumableEN,
	                Parameters.ConsumableNI,
	                Parameters.ConsumableTY,
	                Parameters.ConsumableBL,
	                Parameters.ConsumableWhole,
	                Parameters.Card1,
	                Parameters.Card2,
	                Parameters.Card3
	            }
	        },
	        {
	            Events.WinStreak,
	            new List<Parameters>
	            {
	                Parameters.StreakNo,
	                Parameters.Bfuel,
	                Parameters.RPBoost,
	                Parameters.StreakType,
	                Parameters.ConsumableEN,
	                Parameters.ConsumableNI,
	                Parameters.ConsumableTY,
	                Parameters.ConsumableBL,
	                Parameters.ConsumableWhole,
	                Parameters.Card1,
	                Parameters.Card2,
	                Parameters.Card3
	            }
	        },
	        {
	            Events.EnterShop,
	            new List<Parameters>
	            {
	                Parameters.FromScreen,
	                Parameters.MlstRce,
	                Parameters.DealCar,
	                Parameters.DealCarPrice,
	                Parameters.DealCashback,
	                Parameters.DealDiscount,
	                Parameters.DealFreeUpgradeLevel
	            }
	        },
	        {
	            Events.EnterCashShop,
	            ParametersLists.CarDealEventsParameters
	        },
	        {
	            Events.EnterGoldShop,
	            ParametersLists.CarDealEventsParameters
	        },
	        {
	            Events.SwipeIAPShop,
	            ParametersLists.ClickSwipeIAP
	        },
	        {
	            Events.ClickIAP,
	            ParametersLists.ClickSwipeIAP
	        },
	        {
	            Events.DealShown,
	            ParametersLists.CarDealEventsParameters
	        },
	        {
	            Events.DealCompleted,
	            ParametersLists.CarDealEventsParameters
	        },
	        {
	            Events.DealBackOut,
	            ParametersLists.CarDealEventsParameters
	        },
	        {
	            Events.DealBackOutCancel,
	            ParametersLists.CarDealEventsParameters
	        },
	        {
	            Events.DealBackOutConfirm,
	            ParametersLists.CarDealEventsParameters
	        },
	        {
	            Events.DailyBattleRewardsRemoved,
	            new List<Parameters>
	            {
	                Parameters.DBRewardsRemoved,
	                Parameters.DBRewardId,
	                Parameters.DBRewardTier,
	                Parameters.DBRewardDate
	            }
	        },
	        {
	            Events.AudioFirstRaceOfSession,
	            new List<Parameters>
	            {
	                Parameters.DeviceModel,
	                Parameters.MusicMuted,
	                Parameters.SFXMuted,
	                Parameters.SystemVolume,
	                Parameters.HeadphonesPluggedIn,
	                Parameters.OtherAudioPlaying
	            }
	        },
	        {
	            Events.CarePackage,
	            new List<Parameters>
	            {
	                Parameters.PackageLevel,
	                Parameters.DCsh,
	                Parameters.DGld,
	                Parameters.FreeUpgs,
	                Parameters.ConsumableEN,
	                Parameters.ConsumableNI,
	                Parameters.ConsumableTY,
	                Parameters.ConsumableBL,
	                Parameters.MlstRce,
	                Parameters.LapseTime,
	                Parameters.CmlPacks,
	                Parameters.CmlLevelPacks,
	                Parameters.Notif
	            }
	        },
	        {
	            Events.WorldTourTutorial,
	            new List<Parameters>
	            {
	                Parameters.RTier,
	                Parameters.Title
	            }
	        },
	        {
	            Events.StarterPackOffered,
	            new List<Parameters>
	            {
	                Parameters.SPTitle,
	                Parameters.SPTime,
	                Parameters.SPDiscount,
	                Parameters.SPPopupIndex,
	                Parameters.MlstRce,
	                Parameters.PinProg,
	                Parameters.BGld,
	                Parameters.BCsh
	            }
	        },
	        {
	            Events.BundlePackOffered,
	            new List<Parameters>
	            {
	                Parameters.SPTitle,
	                Parameters.SPTime,
	                Parameters.SPDiscount,
	                Parameters.SPPopupIndex,
	                Parameters.MlstRce,
	                Parameters.PinProg,
	                Parameters.BGld,
	                Parameters.BCsh
	            }
	        },
	        {
	            Events.LastChanceOffered,
	            new List<Parameters>
	            {
	                Parameters.SPTitle,
	                Parameters.SPTime,
	                Parameters.SPDiscount,
	                Parameters.SPPopupIndex,
	                Parameters.MlstRce,
	                Parameters.PinProg,
	                Parameters.BGld,
	                Parameters.BCsh
	            }
	        },
	        {
	            Events.StartPackBought,
	            new List<Parameters>
	            {
	                Parameters.SPTitle,
	                Parameters.SPTime,
	                Parameters.SPDiscount,
	                Parameters.SPPopupIndex,
	                Parameters.MlstRce,
	                Parameters.PinProg,
	                Parameters.BGld,
	                Parameters.BCsh
	            }
	        },
	        {
	            Events.ShowroomClassicsPromo,
	            new List<Parameters>
	            {
	                Parameters.MlstRce,
	                Parameters.CmlRCmp,
	                Parameters.BGld,
	                Parameters.BCsh,
	                Parameters.Bfuel,
	                Parameters.SelCar
	            }
	        },
	        {
	            Events.BundlePackBought,
	            new List<Parameters>
	            {
	                Parameters.SPTitle,
	                Parameters.SPTime,
	                Parameters.SPDiscount,
	                Parameters.SPPopupIndex,
	                Parameters.MlstRce,
	                Parameters.PinProg,
	                Parameters.BGld,
	                Parameters.BCsh
	            }
	        },
	        {
	            Events.DismissedRateApp,
	            ParametersLists.Empty
	        },
	        {
	            Events.ConfirmedRateApp,
	            ParametersLists.Empty
	        },
	        {
	            Events.SpotPrize,
	            new List<Parameters>
	            {
	                Parameters.PrizeLvl,
	                Parameters.MPEvtID,
	                Parameters.MPEvtRace,
	                Parameters.SptPrize
	            }
	        },
	        {
	            Events.TestUpgrade,
	            new List<Parameters>()
	        },
	        {
	            Events.ChooseYourName,
	            new List<Parameters>()
	            {
	                Parameters.PName,
	                Parameters.PAvtr,
	            }
	        },
	        {
	            Events.TapInstagram,
	            new List<Parameters>()
	        },
	        {
	            Events.TapTelegram,
	            new List<Parameters>()
	        },
	        {
	            Events.InstagramReward,
	            new List<Parameters>()
	            {
	                Parameters.BGld,
	                Parameters.BCsh,
	                Parameters.DGld,
	                Parameters.DCsh,
	                Parameters.tme,
                }
	        },
	        {
	            Events.TelegramReward,
	            new List<Parameters>()
	            {
	                Parameters.BGld,
	                Parameters.BCsh,
	                Parameters.DGld,
	                Parameters.DCsh,
	                Parameters.tme,
                }
	        },
	        {
	            Events.LeaderboardReward,
	            new List<Parameters>()
	            {
	                Parameters.BGld,
	                Parameters.BCsh,
	                Parameters.DGld,
	                Parameters.DCsh,
	                Parameters.tme,
	                Parameters.rnk,
	            }
	        },
			{
				Events.FirstTimePurchase,
				new List<Parameters>
				{
					Parameters.Itm,
					Parameters.Currency,
					Parameters.Price
				}
			},
			{
				Events.JumpInClearFuelTimer,
				new List<Parameters>()
				{
					Parameters.FirstTimeZone,
					Parameters.SecondTimeZone
				}
			},
			{
				Events.AppsFlyerValidationStart,
				new List<Parameters>
				{
					Parameters.UserID,
					Parameters.ProductID,
					Parameters.TransactionID,
					Parameters.Signature,
					Parameters.ErrorText
				}
			},
			{
				Events.AppsFlyerValidationFail,
				new List<Parameters>
				{
					Parameters.UserID,
					Parameters.ProductID,
					Parameters.TransactionID,
					Parameters.Signature,
					Parameters.ErrorText
				}
			},
			{
				Events.AppsFlyerValidationSuccess,
				new List<Parameters>
				{
					Parameters.UserID,
					Parameters.ProductID,
					Parameters.TransactionID,
					Parameters.Signature,
					Parameters.ErrorText
				}
			},
			{
				Events.PurchaseStart,
				new List<Parameters>
				{
					Parameters.Itm,
					Parameters.Currency,
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone
				}
			},
			{
				Events.DeferredPurchase,
				new List<Parameters>
				{
					Parameters.Itm,
					Parameters.Currency,
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone
				}
			},
			{
				Events.PurchaseSuccess,
				new List<Parameters>
				{
					Parameters.Itm,
					Parameters.Currency,
					Parameters.Price,
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone
				}
			},
			{
				Events.PurchaseFail,
				new List<Parameters>
				{
					Parameters.Itm,
					Parameters.Currency,
					Parameters.Price,
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone,
					Parameters.ErrorDomain,
					Parameters.ErrorCode,
				}
			},
			{
				Events.PurchaseCancel,
				new List<Parameters>
				{
					Parameters.Itm,
					Parameters.Currency,
					Parameters.Price,
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone
				}
			},
			{
				Events.PurchaseShopOpen,
				new List<Parameters>
				{
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone
				}
			},
			{
				Events.PurchaseShopCategoryClick,
				new List<Parameters>
				{
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone,
					Parameters.ShopCategory
				}
			},
			{
				Events.PurchaseShopItemClick,
				new List<Parameters>
				{
					Parameters.UserID,
					Parameters.UIScreenID,
					Parameters.Market,
					Parameters.TimeZone,
					Parameters.Itm
				}
			},
			{
				Events.OnlineRace,
				new List<Parameters>
				{
					Parameters.OnlineRaceNumber,
					Parameters.OnlineRaceLosesCount
				}
			}
		};
	}
}
