// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_1_second_win = "CgkI7YbU2agdEAIQFA"; // <GPGSID>
        public const string achievement_class_3_passed = "CgkI7YbU2agdEAIQCA"; // <GPGSID>
        public const string achievement_halfway_class_5 = "CgkI7YbU2agdEAIQHA"; // <GPGSID>
        public const string achievement_lets_go = "CgkI7YbU2agdEAIQAQ"; // <GPGSID>
        public const string achievement_001_second_loser = "CgkI7YbU2agdEAIQFg"; // <GPGSID>
        public const string achievement_great_wheel_spin = "CgkI7YbU2agdEAIQEA"; // <GPGSID>
        public const string achievement_gear_shifter = "CgkI7YbU2agdEAIQFw"; // <GPGSID>
        public const string achievement_halfway_class_1 = "CgkI7YbU2agdEAIQAw"; // <GPGSID>
        public const string achievement_halfway_class_3 = "CgkI7YbU2agdEAIQBw"; // <GPGSID>
        public const string achievement_halfway_class_2 = "CgkI7YbU2agdEAIQBQ"; // <GPGSID>
        public const string achievement_beat_olivia = "CgkI7YbU2agdEAIQDA"; // <GPGSID>
        public const string achievement_halfway_class_4 = "CgkI7YbU2agdEAIQCQ"; // <GPGSID>
        public const string achievement_get_a_nissan = "CgkI7YbU2agdEAIQJA"; // <GPGSID>
        public const string achievement_get_a_cheverolet = "CgkI7YbU2agdEAIQIw"; // <GPGSID>
        public const string achievement_beat_damian = "CgkI7YbU2agdEAIQDQ"; // <GPGSID>
        public const string achievement_full_upgrade = "CgkI7YbU2agdEAIQGA"; // <GPGSID>
        public const string achievement_get_a_ford = "CgkI7YbU2agdEAIQJw"; // <GPGSID>
        public const string achievement_get_a_audi = "CgkI7YbU2agdEAIQJQ"; // <GPGSID>
        public const string achievement_spend_5_milion_cash = "CgkI7YbU2agdEAIQHg"; // <GPGSID>
        public const string achievement_tuner = "CgkI7YbU2agdEAIQIA"; // <GPGSID>
        public const string achievement_class_1_passed = "CgkI7YbU2agdEAIQBA"; // <GPGSID>
        public const string achievement_180_speed = "CgkI7YbU2agdEAIQEw"; // <GPGSID>
        public const string achievement_beat_all_the_leaders = "CgkI7YbU2agdEAIQDw"; // <GPGSID>
        public const string achievement_001_second_winner = "CgkI7YbU2agdEAIQFQ"; // <GPGSID>
        public const string achievement_class_5_passed = "CgkI7YbU2agdEAIQHQ"; // <GPGSID>
        public const string achievement_get_a_bmw = "CgkI7YbU2agdEAIQIg"; // <GPGSID>
        public const string achievement_buy_40_cars = "CgkI7YbU2agdEAIQGw"; // <GPGSID>
        public const string achievement_gold_spender = "CgkI7YbU2agdEAIQIQ"; // <GPGSID>
        public const string achievement_class_4_passed = "CgkI7YbU2agdEAIQCg"; // <GPGSID>
        public const string achievement_buy_18_cars = "CgkI7YbU2agdEAIQGg"; // <GPGSID>
        public const string achievement_15_seconds_win = "CgkI7YbU2agdEAIQEg"; // <GPGSID>
        public const string achievement_get_a_minicooper = "CgkI7YbU2agdEAIQJg"; // <GPGSID>
        public const string achievement_beat_ethan = "CgkI7YbU2agdEAIQDg"; // <GPGSID>
        public const string achievement_tune_your_car = "CgkI7YbU2agdEAIQHw"; // <GPGSID>
        public const string achievement_class_2_passed = "CgkI7YbU2agdEAIQBg"; // <GPGSID>
        public const string achievement_10_seconds_win = "CgkI7YbU2agdEAIQEQ"; // <GPGSID>
        public const string achievement_beat_charlie = "CgkI7YbU2agdEAIQCw"; // <GPGSID>
        public const string achievement_buy_a_car_from_each_class = "CgkI7YbU2agdEAIQGQ"; // <GPGSID>

}

