using System;

public enum ProgressionMapPinEventType
{
    TUTORIAL_RACES,
    REGULATION_RACES,
    CREW_RACES,
	DAILY_BATTLES,
	LADDER_RACES,
	MECHANIC,
	DAILY_BATTLE_RACES,
	FRIENDS_RACES,
	RESTRICTION_RACES,
	CAR_SPECIFIC_RACES,
	MANUFACTURER_SPECIFIC_RACES,
    TOURNAMENT_RACES,
    MULTIPLAYER_RACES,
    SMP_RACES,
    WORLD_TOURS
}
